AnnurCrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("organizer.urls")),
    path("student/", include("student.urls")),
    path("mentor/", include("mentor.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin/urls.py
from django.urls import path
from .views import (
    index, reyting,
    mentor, student,
    info, user
)

urlpatterns = [
    path("index/", index, name="index"),
    path("reyting/", reyting, name="reyting"),
    path("mentor/", mentor, name="mentor"),
    path("student/", student, name="student"),
    path("info/", info, name="info"),
    path("user/", user, name="user"),
]

mentor/urls.py
from django.urls import path
from .views import (
    index, reyting,
    group, student,
    info, user
)

app_name = 'mentor'

urlpatterns = [
    path("index/", index, name="index"),
    path("reyting/", reyting, name="reyting"),
    path("group/", group, name="group"),
    path("student/", student, name="student"),
    path("info/", info, name="info"),
    path("user/", user, name="user"),
]

organizer/urls.py
from django.urls import path
from .views import (
    index, reyting,
    mentor, student,
    info, user, grade,
    request, annu_index
)

app_name = "organizer"

urlpatterns = [
    path("index/", index, name="index"),
    path("reyting/", reyting, name="reyting"),
    path("mentor/", mentor, name="mentor"),
    path("student/", student, name="student"),
    path("info/", info, name="info"),
    path("user/", user, name="user"),
    path("grade/", grade, name="grade"),

    path("request/", request, name="request"),
    path("", annu_index, name="annu_index"),
]

student/urls.py
from django.urls import path
from .views import group, info, reyting, shop, students


app_name = 'student'

urlpatterns = [
    path('group/', group, name='group'),
    path('info/', info, name='info'),
    path('reyting/', reyting, name='reyting'),
    path('shop/', shop, name='shop'),
    path('students/', students, name='students')
]

mentor/models.py
from django.db import models
from shared.models import BaseModel
from .validators import  (
    name_validator, validate_image_format, 
    validate_image_size, phone_number_validator 
)


class Mentor(BaseModel):
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]
    
    TEACHING_AREA_CHOICES = [
        ('backend', 'Backend'),
        ('frontend', 'Frontend'),
        ('graphic_design', 'Graphic Design'),
    ]

    first_name = models.CharField(
        max_length=50,
        validators=[name_validator]   
    )
    last_name = models.CharField(
        max_length=50,
        validators=[name_validator]   
    )
    image = models.ImageField(
        upload_to='mentors/',
        validators=[validate_image_format, validate_image_size]  
    )
    phone_number = models.CharField(
        max_length=15,
        validators=[phone_number_validator]  
    )
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    birth_year = models.PositiveIntegerField()
    teaching_area = models.CharField(max_length=15, choices=TEACHING_AREA_CHOICES)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

organizer/models.py
from django.db import models
from shared.models import BaseModel
from mentor.models import Mentor
from .validators import validate_start_time, validate_end_time   

class Group(BaseModel):
    GROUP_AREA_CHOICES = [
        ('backend', 'Backend'),
        ('frontend', 'Frontend'),
        ('graphic_design', 'Graphic Design'),
    ]
    name = models.CharField(max_length=100)  
    type = models.CharField(max_length=15, choices=GROUP_AREA_CHOICES)

    def __str__(self):
        return self.name
    


class MentorGroups(BaseModel):
    mentor = models.ForeignKey(Mentor, on_delete=models.CASCADE)   
    group = models.ForeignKey(Group, on_delete=models.CASCADE) 
    start_time = models.TimeField(validators=[validate_start_time])   
    end_time = models.TimeField()  

    def clean(self):
        validate_end_time(self.end_time, self.start_time)   

    def __str__(self):
        return f"{self.name} ({self.start_time.strftime('%H:%M')} - {self.end_time.strftime('%H:%M')})"
  

    def __str__(self):
        return f"{self.mentor} - {self.group}"

shared/models.py
from django.db import models

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)    
    updated_at = models.DateTimeField(auto_now=True)   

    class Meta:
        abstract = True  

student/models.py
from django.db import models
from organizer.models import Group
from .validators import  (
    name_validator, validate_image_format, 
    validate_image_size, phone_number_validator 
)
from shared.models import BaseModel
 

class Student(BaseModel):
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]

    STATUS_CHOICES = [
        ('starting', 'Starting'),
        ('studying', 'Studying'),
        ('not_studying', 'Not Studying'),
    ]

    first_name = models.CharField(
        max_length=50,
        validators=[name_validator]   
    )
    last_name = models.CharField(
        max_length=50,
        validators=[name_validator]   
    )
    image = models.ImageField(
        upload_to='mentors/',
        validators=[validate_image_format, validate_image_size]  
    )
    phone_number = models.CharField(
        max_length=15,
        validators=[phone_number_validator]  
    )    
    birth_year = models.PositiveIntegerField()
    group = models.ForeignKey(Group, on_delete=models.CASCADE)   
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='starting')  # Holat
    username = models.CharField(max_length=150, unique=True)  # Foydalanuvchi nomi
    password = models.CharField(max_length=128)  # Parol
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)

    silver = models.PositiveIntegerField(default=0)  # Silver maydoni, dastlabki qiymati 0

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

admin/views.py
from django.shortcuts import render

 
def index(request):
    return render(request, 'admin/index.html', {})


def mentor(request):
    return render(request, 'admin/mentor.html', {})


def info(request):
    return render(request, 'admin/info.html', {})


def reyting(request):
    return render(request, 'admin/reyting.html', {})


def student(request):
    return render(request, 'admin/student.html', {})


def user(request):
    return render(request, 'admin/user.html', {})

mentor/views.py
from django.shortcuts import render

 
def index(request):
    return render(request, 'mentor/index.html', {})


def group(request):
    return render(request, 'mentor/group.html', {})


def info(request):
    return render(request, 'mentor/info.html', {})


def reyting(request):  # noqa
    return render(request, 'mentor/reyting.html', {})


def student(request):
    return render(request, 'mentor/student.html', {})


def user(request):
    return render(request, 'mentor/user.html', {})

organizer/views.py
from django.shortcuts import render
from .models import Group
 
def index(request):
    return render(request, 'admin/index.html', {})


def mentor(request):
    return render(request, 'organizer/mentor.html', {})


def info(request):
    return render(request, 'organizer/info.html', {})


def reyting(request):
    return render(request, 'organizer/reyting.html', {})


def student(request):
    return render(request, 'organizer/students.html', {})


def user(request):
    return render(request, 'organizer/user.html', {})

def grade(request):
    return render(request, 'adorganizermin/grade/grade.html', {})



def annu_index(request):
    return render(request, 'annur-site/index.html', {})


def request(request):
    return render(request, 'annur-site/request.html', {})

shared/views.py
from django.shortcuts import render

# Create your views here.

student/views.py
from django.shortcuts import render


def group(request):
    return render(request, 'student/group.html', {})


def info(request):
    return render(request, 'student/info.html', {})


def reyting(request):  # noqa
    return render(request, 'student/reyting.html', {})


def students(request):
    return render(request, 'student/students.html', {})


def shop(request):
    return render(request, 'student/shop.html', {})

templates/mentor/group.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'annur-site/assets/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'annur-site/assets/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'annur-site/assets/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'annur-site/assets/favicon/site.webmanifest' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'mentor/assets/libs/grid.css' %}">
    <link rel="stylesheet" href="{% static 'mentor/style.css' %}">
    <link rel="stylesheet" href="{% static 'mentor/style.css' %}">
    <title>AN NUR Mentor</title>
</head>

<body>

    <!-- Header starting -->
    <header>
        <nav>
            <div class="row">
                <div class="col-3 col-xl-4 col-md-6 col-sm-8">
                    <div class="header-box">
                        <i class="fa fa-bars"></i>
                        <a href="#!" class="logo">
                            <img src="{% static 'annur-site/assets/images/logo.svg' %}" alt="logo">
                        </a>
                    </div>
                </div>
            </div>
            <a href=".{% url 'mentor:index' %}"> <i class="fa-solid fa-arrow-right-from-bracket"></i></a>
        </nav>

        <div class="header-mobile">
            <ul>
                <li>
                    <a href="{% url 'mentor:group' %}"><i class="fa-solid fa-users-line"></i> Groups</a>
                </li>
                <li>
                    <a href="{% url 'mentor:student' %}"><i class="fa-solid fa-graduation-cap"></i> Student</a>
                </li>
                <li>
                    <a href="{% url 'mentor:reyting' %}"><i class="fa-solid fa-chart-simple"></i> Reyting</a>
                </li>
                <li>
                    <a href="{% url 'mentor:user' %}"><i class="fa-solid fa-chart-simple"></i> Users</a>
                </li>
                <li>
                    <a href="./index.html"><i class="fa-solid fa-gear"></i> Info</a>
                </li>
            </ul>
            <i class="fa fa-close"></i>
        </div>
    </header>

    <!-- Main starting -->
    <main>
        <div class="wrap">
            <div class="sidebar">
                <ul>
                    <li>
                        <a href="{% url 'mentor:group' %}"><i class="fa-solid fa-people-group"></i>Groups</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:student' %}"><i class="fa-solid fa-graduation-cap"></i> Student</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:reyting' %}"><i class="fa-solid fa-chart-simple"></i> Reyting</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:user' %}"><i class="fa-solid fa-user-plus"></i> New users</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:info' %}"><i class="fa-solid fa-gear"></i>Info</a>
                    </li>
                </ul>
            </div>
            <div class="groups-content main-content">
                <h1 class="title">Groups</h1>
                <ul>
                    <li><span>1-group</span></li>
                    <li><span>2-group</span></li>
                    <li><span>3-group</span></li>
                    <li><span>4-group</span></li>
                    <li><span>5-group</span></li>
                    <li><span>6-group</span></li>
                </ul>
                <a href="{% url 'mentor:user' %}" class="createGroup">Create Group</a>
            </div>
        </div>
    </main>

    <script src="{% static 'mentor/script.js' %}"></script>
</body>

</html>

templates/mentor/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'annur-site/assets/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'annur-site/assets/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'annur-site/assets/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'annur-site/assets/favicon/site.webmanifest' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'mentor/assets/libs/grid.css' %}">
    <link rel="stylesheet" href="{% static 'mentor/style.css' %}">
    <link rel="stylesheet" href="{% static 'mentor/students.css' %}">
    <title>AN NUR Mentor</title>
</head>

<body>

    <!-- Header starting -->
    <header>
        <nav>
            <div class="row">
                <div class="col-3 col-xl-4 col-md-6 col-sm-8">
                    <div class="header-box">
                        <i class="fa fa-bars"></i>
                        <a href="#!" class="logo">
                            <img src="{% static 'annur-site/assets/images/logo.svg' %}" alt="logo">
                        </a>
                    </div>
                </div>
            </div>
            <a href="{% url 'mentor:index' %}"> <i class="fa-solid fa-arrow-right-from-bracket"></i></a>
        </nav>

        <div class="header-mobile">
            <ul>
                <li>
                    <a href="{% url 'mentor:group' %}"><i class="fa-solid fa-users-line"></i> Groups</a>
                </li>
                <li>
                    <a href="{% url 'mentor:student' %}"><i class="fa-solid fa-graduation-cap"></i> Student</a>
                </li>
                <li>
                    <a href="{% url 'mentor:reyting' %}"><i class="fa-solid fa-chart-simple"></i> Reyting</a>
                </li>
                <li>
                    <a href="{% url 'mentor:user' %}"><i class="fa-solid fa-chart-simple"></i> Users</a>
                </li>
                <li>
                    <a href="{% url 'mentor:info' %}"><i class="fa-solid fa-gear"></i>Info</a>
                </li>
            </ul>
            <i class="fa fa-close"></i>
        </div>
    </header>

    <!-- Main starting -->
    <main>
        <div class="wrap">
            <div class="sidebar">
                <ul>
                    <li>
                        <a href="{% url 'mentor:group' %}"><i class="fa-solid fa-people-group"></i>Groups</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:student' %}"><i class="fa-solid fa-graduation-cap"></i> Student</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:reyting' %}"><i class="fa-solid fa-chart-simple"></i>Reyting</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:user' %}"><i class="fa-solid fa-user-plus"></i> New users</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:info' %}"><i class="fa-solid fa-gear"></i>Info</a>
                    </li>
                </ul>
            </div>
            <div class="students-content main-content">
                <h1 class="title">Reyting</h1>
                <table>
                    <tr>
                        <th>№</th>
                        <th>Ism familya</th>
                        <th>Kurs</th>
                        <th>Holati</th>
                        <th>XP</th>
                        <th>Kumush</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bexruz Jalolov</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>lorem ipsum</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>lorem ipsum</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>lorem ipsum</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                </table>
            </div>
        </div>
    </main>

    <script src="{% static 'mentor/script.js' %}"></script>
</body>

</html>

templates/mentor/reyting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'annur-site/assets/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'annur-site/assets/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'annur-site/assets/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'annur-site/assets/favicon/site.webmanifest' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'annur-site/assets/libs/grid.css' %}">
    <link rel="stylesheet" href="{% static 'annur-site/style.css' %}">
    <link rel="stylesheet" href="{% static 'mentor/students.css' %}">
    <title>AN NUR Mentor</title>
</head>

<body>

    <!-- Header starting -->
    <header>
        <nav>
            <div class="row">
                <div class="col-3 col-xl-4 col-md-6 col-sm-8">
                    <div class="header-box">
                        <i class="fa fa-bars"></i>
                        <a href="#!" class="logo">
                            <img src="{% static '/annur-site/assets/images/logo.svg' %}" alt="logo">
                        </a>
                    </div>
                </div>
            </div>
            <a href="{% url 'mentor:index' %}"> <i class="fa-solid fa-arrow-right-from-bracket"></i></a>
        </nav>

        <div class="header-mobile">
            <ul>
                <li>
                    <a href="{% url 'mentor:group' %}"><i class="fa-solid fa-users-line"></i> Groups</a>
                </li>
                <li>
                    <a href="{% url 'mentor:student' %}"><i class="fa-solid fa-graduation-cap"></i> Student</a>
                </li>
                <li>
                    <a href="{% url 'mentor:reyting' %}"><i class="fa-solid fa-chart-simple"></i> Reyting</a>
                </li>
                <li>
                    <a href="./user.html"><i class="fa-solid fa-user-plus"></i> New users</a>
                </li>
                <li>
                    <a href="{% url 'mentor:info' %}"><i class="fa-solid fa-gear"></i> Info</a>
                </li>
            </ul>
            <i class="fa fa-close"></i>
        </div>
    </header>

    <!-- Main starting -->
    <main>
        <div class="wrap">
            <div class="sidebar">
                <ul>
                    <li>
                        <a href="{% url 'mentor:group' %}"><i class="fa-solid fa-users-line"></i> Groups</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:student' %}"><i class="fa-solid fa-graduation-cap"></i> Student</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:reyting' %}"><i class="fa-solid fa-chart-simple"></i> Reyting</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:user' %}"><i class="fa-solid fa-user-plus"></i> New users</a>
                    </li>
                    <li>
                        <a href="{% url 'mentor:info' %}"><i class="fa-solid fa-gear"></i> Info</a>
                    </li>
                </ul>
            </div>
            <div class="main-content">
                <h1 class="title">Reyting</h1>
                <table>
                    <tr>
                        <th>№</th>
                        <th>Ism familya</th>
                        <th>Kurs</th>
                        <th>Holati</th>
                        <th>Bosqich</th>
                        <th>XP</th>
                        <th>Kumush</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bexruz Jalolov</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>3</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>lorem ipsum</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>3</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>lorem ipsum</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>3</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>lorem ipsum</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>3</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                </table>
            </div>
        </div>
    </main>


    <script src="{% static 'mentor/script.js' %}"></script>
</body>

</html>

templates/organizer/students.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'annur-site/assets/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'annur-site/assets/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'annur-site/assets/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'annur-site/assets/favicon/site.webmanifest' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'admin/assets/libs/grid.css' %}">
    <link rel="stylesheet" href="{% static 'admin/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/students.css' %}">
    <title>AN NUR ADMIN</title>
</head>

<body>

    <!-- Header starting -->
    <header>
        <nav>
            <div class="row">
                <div class="col-3 col-xl-4 col-md-6 col-sm-8">
                    <div class="header-box">
                        <i class="fa fa-bars"></i>
                        <a href="#!" class="logo">
                            <img src="{% static 'admin/assets/images/logo.svg' %}" alt="logo">
                        </a>
                    </div>
                </div>
            </div>
            <i class="fa-solid fa-arrow-right-from-bracket"></i>
        </nav>

        <div class="header-mobile">
            <ul>
                <li>
                    <a href="{% url 'organizer:index' %}"><i class="fa-solid fa-users-line"></i> Groups</a>
                </li>
                <li>
                    <a href="{% url 'organizer:student' %}"><i class="fa-solid fa-graduation-cap"></i> Student</a>
                </li>
                <li>
                    <a href="{% url 'organizer:mentor' %}"><i class="fa-solid fa-people-group"></i> Mentor CRUD</a>
                </li>
                <li>
                    <a href="{% url 'organizer:reyting' %}"><i class="fa-solid fa-chart-simple"></i> Reyting</a>
                </li>
                <li>
                    <a href="{% url 'organizer:user' %}"><i class="fa-solid fa-user-plus"></i> New users</a>
                </li>
                <li>
                    <a href="{% url 'organizer:info' %}"><i class="fa-solid fa-gear"></i> Info</a>
                </li>
            </ul>
            <i class="fa fa-close"></i>
        </div>
    </header>

    <!-- Main starting -->
    <main>
        <div class="wrap">
            <div class="sidebar">
                <ul>
                    <li>
                        <a href="{% url 'organizer:index' %}"><i class="fa-solid fa-users-line"></i> Groups</a>
                    </li>
                    <li>
                        <a href="{% url 'organizer:student' %}"><i class="fa-solid fa-graduation-cap"></i> Student</a>
                    </li>
                    <li>
                        <a href="{% url 'organizer:mentor' %}"><i class="fa-solid fa-people-group"></i> Mentor CRUD</a>
                    </li>
                    <li>
                        <a href="{% url 'organizer:reyting' %}"><i class="fa-solid fa-chart-simple"></i> Reyting</a>
                    </li>
                    <li>
                        <a href="{% url 'organizer:user' %}"><i class="fa-solid fa-user-plus"></i> New users</a>
                    </li>
                    <li>
                        <a href="{% url 'organizer:info' %}"><i class="fa-solid fa-gear"></i> Info</a>
                    </li>
                </ul>
            </div>
            <div class="main-content">
                <h1 class="title">Students</h1>
                <table>
                    <tr>
                        <th>№</th>
                        <th>Ism familya</th>
                        <th>Kurs</th>
                        <th>Holati</th>
                        <th>Bosqich</th>
                        <th>XP</th>
                        <th>Kumush</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bexruz Jalolov</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>3</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>lorem ipsum</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>3</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>lorem ipsum</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>3</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>lorem ipsum</td>
                        <td>Grafik dizayn</td>
                        <td>O‘qiyabdi</td>
                        <td>3</td>
                        <td>2511</td>
                        <td>1582</td>
                    </tr>
                </table>
                <a href="{% url 'organizer:grade' %}" class="studentGrade">Grade</a>
            </div>
        </div>
    </main>

    <script src="{% static 'admin/script.js' %}"></script>
</body>

</html>